### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ZhenhaoH** [vlongle/articulate-anything#1]
Hi, I'm trying to articulate the PartNet-Mobility objects by running articulate_partnet.ipynb, but I got the following error when executing `steps = articulate(cfg)`:
```bash
INFO:root:GT joint diff is {'joint_type': True, 'joint_origin': {'xyz': 0.768917014656568, 'orientation': 0.0}, 'joint_axis': 0.0, 'joint_limit': {'direction_diff': 0.0, 'range_diff': 1.2566370614359168}}
INFO:root:JointCriticMultiModalExamples: Generating content.
ERROR:root:Failed to run actor-critic loop for iteration 0, seed 0:
ERROR:root:Traceback (most recent call last):
  File "/home/zh/articulate-anything/actor_critic.py", line 62, in actor_critic_loop
    critic_result = critic_func(iteration, seed, actor_result)
  File "/home/zh/articulate-anything/articulate_joint.py", line 263, in <lambda>
    lambda i, s, a: critic_function(i, s, cfg, prompt, a),
  File "/home/zh/articulate-anything/articulate_joint.py", line 209, in critic_function
    joint_critic.generate_prediction(gt_video_path=cfg.prompt,
  File "/home/zh/articulate-anything/articulate_anything/agent/agent.py", line 94, in generate_prediction
    prompt_parts = self.make_prompt_parts(*args, **kwargs)
  File "/home/zh/articulate-anything/articulate_anything/agent/agent.py", line 64, in make_prompt_parts
    prompt_parts = self._make_prompt_parts(*args, **kwargs)
  File "/home/zh/articulate-anything/articulate_anything/agent/multimodal_incontext_agent.py", line 12, in _make_prompt_parts
    prompt_parts.extend(self._get_in_context_examples())  # examples
  File "/home/zh/articulate-anything/articulate_anything/agent/multimodal_incontext_agent.py", line 28, in _get_in_context_examples
    formatted_example = self._format_content(**example_kwargs)
  File "/home/zh/articulate-anything/articulate_anything/agent/critic/joint_prediction/joint_critic.py", line 241, in _format_content
    joint_critic_response = load_json(expected_joint_critic_path)
  File "/home/zh/articulate-anything/articulate_anything/utils/utils.py", line 41, in load_json
    with open(filename, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/multi_modal_incontext_examples/joint_critic/in_context_examples_datasets/joint_axis/48167/joint_0/joint_critic.json'

INFO:root:At iteration 0, seed 0, Best result so far {'iteration': 0, 'seed': 0, 'feedback_score': -1}
INFO:root:JointPredictionActor: Generating content.
ERROR:root:Failed to run actor-critic loop for iteration 1, seed 0:
ERROR:root:Traceback (most recent call last):
  File "/home/zh/articulate-anything/actor_critic.py", line 60, in actor_critic_loop
    actor_result = actor_func(iteration, seed, retry_kwargs)
  File "/home/zh/articulate-anything/articulate_joint.py", line 262, in <lambda>
    lambda i, s, r: actor_function(i, s, cfg, prompt, gpu_id, r),
  File "/home/zh/articulate-anything/articulate_joint.py", line 180, in actor_function
    joint_actor.generate_prediction(gt_input=cfg.prompt,
  File "/home/zh/articulate-anything/articulate_anything/agent/agent.py", line 94, in generate_prediction
    prompt_parts = self.make_prompt_parts(*args, **kwargs)
  File "/home/zh/articulate-anything/articulate_anything/agent/agent.py", line 64, in make_prompt_parts
    prompt_parts = self._make_prompt_parts(*args, **kwargs)
TypeError: _make_prompt_parts() missing 1 required positional argument: 'link_placement_path'

INFO:root:At iteration 1, seed 0, Best result so far {'iteration': 1, 'seed': 0, 'feedback_score': -1}
INFO:root:Pipeline execution completed
INFO:root:Steps executed: Mesh Retrieval, Link actor, Link critic, Link Articulation, Joint actor, Joint critic, Joint Articulation
```
It seems this joint_critic.json file disappeared somehow. Do you know how to fix this?

**Comment by vlongle** [comment]
Thanks for raising the issue!

I've uploaded the joint_critic.json files. Please let me know if you still run into this problem.

**Comment by ZhenhaoH** [comment]
Thank you so much. It works now.
